project:
  id: 56bbafc3-a52c-4a25-b385-aa74fd6b7b9e
  name: Obitanus Abitonus
  description: >-
    A simple LaTeX template for obituaries
  authors:
    - name: Kvn Dtrx
      mail: kvn.dtrx+git@protonmail.ch
  license:
    type: MIT
    year: 2025
    file: LICENSE.txt
forges:
  github:
    url: https://github.com/kvn-dtrx/obitanus-abitonus
    visibility: public
